/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package game;
/**
 *
 * @author Zach
 */
public class rulesPage extends javax.swing.JFrame {

    /**
     * Creates new form rulesPage
     */
    public rulesPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        optMenu = new javax.swing.JMenu();
        closeMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Rules of Blackjack");
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane2.setBorder(null);
        jScrollPane2.setMaximumSize(new java.awt.Dimension(1280, 720));
        jScrollPane2.setMinimumSize(new java.awt.Dimension(1280, 720));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(1280, 720));

        jTextArea2.setEditable(false);
        jTextArea2.setBackground(new java.awt.Color(0, 195, 0));
        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setText("Rules:\n\n\tThe goal of blackjack is to get 21 or as close to it but not over as possible.  The player that is the closest or at 21 is the winner.\tCards \n2-10 are worth their respective values.  Jacks, Queens, and Kings are worth 10.  Aces are initially worth 11, but switch to 1 if the player's hand\nis over 21.\n\n\tAt the beginning of each hand (or round), the user must select a bet from the dropdown menu.  If one of the players doesn't have enough chips,\n the bet will be set to the lowest amount of chips among the remaining players.  These bets go into the pot to be distributed to the hand winner.  \n\n\tEach player will then be dealt two cards.  Only the first card of each computer player will be visible to the user.\n\n\tThe user can then either hit (take another card) or stay.  If you stay, you are no longer allowed to hit for the rest of the hand, so the value\nyou have when you stay is the value that will be compared to other players at the end of the round.\n\n\tOnce everyone has chose to stay or gone above 21, a winner will be determined and the pot distributed.  In the event of a tie, the pot is\ndistributed evenly amongst all the winners.  In the event all players go over 21, nobody wins the pot.\n\n\tA player is eliminated when their chips reach 0, and a winner is the last person with chips remaining.\n\n\n\nNotes:\n\n\tThe choices each player makes is visible in the dialog box for reviewing purposes.");
        jTextArea2.setMaximumSize(new java.awt.Dimension(1280, 720));
        jTextArea2.setMinimumSize(new java.awt.Dimension(1280, 720));
        jTextArea2.setPreferredSize(new java.awt.Dimension(1280, 720));
        jScrollPane2.setViewportView(jTextArea2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        optMenu.setText("Options");

        closeMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        closeMenuItem.setText("Close");
        closeMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeMenuItemActionPerformed(evt);
            }
        });
        optMenu.add(closeMenuItem);

        jMenuBar1.add(optMenu);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeMenuItemActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_closeMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(rulesPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(rulesPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(rulesPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(rulesPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new rulesPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem closeMenuItem;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JMenu optMenu;
    // End of variables declaration//GEN-END:variables
}
